# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {

  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  services.qemuGuest.enable = true;

  # Basic VM settings
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
    autoResize = true;
  };
  boot = {
    growPartition = true;
    kernelParams = [ "console=ttyS0" ];
    loader.grub.device = "/dev/vda";
    loader.timeout = 5;
    tmp.useTmpfs = false;
  };
  # config to fix the `no space left`
  # error during nix build
  fileSystems."/tmp" = {
    fsType = "tmpfs";
    device = "tmpfs";
    options = [ "nosuid" "nodev" "relatime" "size=2G" ];
  };


  # Some optimized Postgres Parameters
  services.postgresql.settings = {
    max_connections = 100;
    shared_buffers = "4GB";
    effective_cache_size = "8GB";
    maintenance_work_mem = "1GB";
    checkpoint_completion_target = 0.9;
    wal_buffers = "16MB";
    default_statistics_target = 100;
    random_page_cost = 1.1;
    effective_io_concurrency = 200;
    work_mem = "19418kB";
    huge_pages = "off";
    min_wal_size = "1GB";
    max_wal_size = "4GB";
    max_worker_processes = 8;
    max_parallel_workers_per_gather = 4;
    max_parallel_workers = 8;
    max_parallel_maintenance_workers = 4;
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

}












