# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, nixos-hardware, ... }: {

  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  services.qemuGuest.enable = true;

  boot = {
    loader.grub = {
      efiSupport = true;
      efiInstallAsRemovable = true;
      device = "nodev";
    };
    tmp.cleanOnBoot = true;
    initrd.kernelModules = [ "nvme" "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" ];
  };

  zramSwap.enable = true;

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-partlabel/ESP";
      fsType = "vfat";
    };

  fileSystems."/" =
    {
      device = "/dev/disk/by-partlabel/nixos";
      fsType = "ext4";
    };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

}
