# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, nixos-hardware, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")

      # import hardware specific configuration
      # https://github.com/NixOS/nixos-hardware/blob/master/lenovo/thinkpad/x1/yoga/7th-gen/default.nix
      nixos-hardware.nixosModules.lenovo-thinkpad-x1-yoga-7th-gen
    ];

  boot = {
    # load kernel modules
    initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
    initrd.kernelModules = [ "dm-snapshot" ];
    kernelModules = [ "kvm-intel" ];
    #kernelPackages = pkgs.unstable.linuxPackages;
    extraModulePackages = with config.boot.kernelPackages; [
      # intel-speed-select
      ivsc-driver
    ];
    supportedFilesystems = [ "ntfs" ];

    loader = {
      # install GRUB
      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
        efiInstallAsRemovable = true;
        useOSProber = true;
        default = "2";
      };
      efi.canTouchEfiVariables = true;
    };
    # encrypt the root partition
    initrd.luks.devices = {
      root = {
        # Get UUID from blkid /dev/nvme0n1p6
        device = "/dev/disk/by-uuid/76db6644-dc9b-4d2a-8424-46a343078284";
        preLVM = true;
        allowDiscards = true;
      };
    };
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/67c8ff2a-1bc2-44f9-9c89-b426f74be4f1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/35E8-E6E6";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/20172ba9-67cb-4d35-97bb-466611233f1a"; }];


  ### Thunderbolt 3 related stuff
  ### We want to use an AMD Radeon GPU when docked, and the Intel GPU when undocked

  # According to https://nixos.wiki/wiki/Thunderbolt, we need this even when not using Gnome
  services.hardware.bolt.enable = true;
  # benefit from Plasma's UI for managing Thunderbolt devices
  environment.systemPackages = with pkgs;[
    plasma5Packages.plasma-thunderbolt
  ];
  # Let's try it without those lines first!
  # # The names of the video drivers the configuration supports.
  # # They will be tried in order until one that supports your card is found.
  # services.xserver.videoDrivers = [
  #   "radeon"
  #   "i810"
  # ];

  # enable all the firmware with a license allowing redistribution
  hardware.enableRedistributableFirmware = true;


  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Fingerprint service options
  services.fprintd.enable = true;
  services.fprintd.tod.enable = true;
  services.fprintd.tod.driver = pkgs.libfprint-2-tod1-goodix;

  #Webcam 
  #  hardware.ipu6 = {
  #    enable = true;
  #    platform = "ipu6ep";
  #  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
