---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

  - name: run flake checks
    commands:
      - nix flake check

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build X1-Yoga
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --out-link result-X1-Yoga
      - nix path-info --closure-size -h $(readlink -f result-X1-Yoga)

trigger:
  branch:
    - main
  event:
    - cron
    - push
    - pull_request

---
kind: pipeline
type: exec
name: nix flake update - amd64

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build X1-Yoga (current)
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --out-link X1-Yoga-current

  - name: nix flake update
    commands:
      - nix flake update

  - name: build X1-Yoga (updated)
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --out-link X1-Yoga-updated

  - name: compare outputs
    commands:
      - nix store diff-closures $(readlink -f X1-Yoga-current) $(readlink -f X1-Yoga-updated)

trigger:
  branch:
    - main
  event:
    - cron
