---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

  - name: run flake checks
    commands:
      - nix flake check # --show-trace

---
kind: pipeline
type: exec
name: build amd64 nixosConfigurations

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build X1-Yoga
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel'
      - nix path-info --closure-size -h $(readlink -f result)

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
