---
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: show flake show
    commands:
      - nix flake show

  - name: show flake info
    commands:
      - nix flake info

  - name: run flake checks
    commands:
      - nix flake check

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build X1-Yoga
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --out-link result-X1-Yoga
      - nix path-info --closure-size -h $(readlink -f result-X1-Yoga)

  - name: Push X1-Yoga to cachix
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push alexanderwallau
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN

  - name: build Netcup-x86
    commands:
      - nix build '.#nixosConfigurations.Netcup-x86.config.system.build.toplevel' --out-link result-Netcup-x86
      - nix path-info --closure-size -h $(readlink -f result-Netcup-x86)

  - name: Push Netcup-x86 to cachix
    commands:
      - nix build '.#nixosConfigurations.Netcup-x86.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push alexanderwallau
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN

trigger:
  branch:
    - main
  event:
    - cron
    - push
    - pull_request

---
kind: pipeline
type: exec
name: build arm64 hosts

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
  - name: build phelps
    commands:
      - nix build '.#nixosConfigurations.phelps.config.system.build.toplevel' --out-link result-phelps
      - nix path-info --closure-size -h $(readlink -f result-phelps)

  - name: Push phelps to cachix
    commands:
      - nix build '.#nixosConfigurations.phelps.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push alexanderwallau
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN


  - name: build kipchoge
    commands:
      - nix build '.#nixosConfigurations.kipchoge.config.system.build.toplevel' --out-link result-kipchoge
      - nix path-info --closure-size -h $(readlink -f result-kipchoge)

  - name: Push kipchoge to cachix
    commands:
      - nix build '.#nixosConfigurations.kipchoge.config.system.build.toplevel' --json | jq -r '.[].outputs | to_entries[].value' | cachix push alexanderwallau
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: CACHIX_AUTH_TOKEN
---
kind: pipeline
type: exec
name: nix flake update - amd64

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build X1-Yoga (current)
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --out-link X1-Yoga-current

  - name: nix flake update
    commands:
      - nix flake update

  - name: build X1-Yoga (updated)
    commands:
      - nix build '.#nixosConfigurations.X1-Yoga.config.system.build.toplevel' --out-link X1-Yoga-updated

  - name: compare outputs
    commands:
      - nix store diff-closures $(readlink -f X1-Yoga-current) $(readlink -f X1-Yoga-updated)

trigger:
  branch:
    - main
  event:
    - cron
