# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, self, ... }: {

  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  services.qemuGuest.enable = true;

  # Basic VM settings
  # Running fstrim weekly is a good idea for VMs.
  # Empty blocks are returned to the host, which can then be used for other VMs.
  # It also reduces the size of the qcow2 image, which is good for backups.
  services.fstrim = {
    enable = true;
    interval = "weekly";
  };
  fileSystems."/"= {
    autoResize = true;
    fsType = "ext4";
  };
  swapDevices = [{
      device = "/var/lib/swapfile";
      # As per tradition double the RAM
      size = 2 * 1024;
    boot.growPartition = true;
    boot = {
      loader = {
        timeout = 10;
        grub = {
          devices = [ primaryDisk ];
          efiSupport = true;
          efiInstallAsRemovable = true;
        };
      };
      initrd = {
        availableKernelModules = [
          "virtio_net"
          "virtio_pci"
          "virtio_mmio"
          "virtio_blk"
          "virtio_scsi"
          "9p"
          "9pnet_virtio"
        ];
        kernelModules = [ "virtio_balloon" "virtio_console" "virtio_rng" ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}