labels:
  backend: local
  platform: linux/arm64
steps:
  - name: Setup Attic
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic login lounge-rocks https://cache.lounge.rocks $ATTIC_KEY --set-default

  - name: Build kipchoge
    image: bash
    commands:
      - nix build '.#nixosConfigurations.kipchoge.config.system.build.toplevel' -o 'result-kipchoge'
      - nix path-info --closure-size -h $(readlink -f 'result-kipchoge')

  - name: Push kipchoge to Attic
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-kipchoge'

  - name: Build phelps
    image: bash
    commands:
      - nix build '.#nixosConfigurations.phelps.config.system.build.toplevel' -o 'result-phelps'
      - nix path-info --closure-size -h $(readlink -f 'result-phelps')

  - name: Push phelps to Attic
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-phelps'

  - name: Build pi4b
    image: bash
    commands:
      - nix build '.#nixosConfigurations.pi4b.config.system.build.toplevel' -o 'result-pi4b'
      - nix path-info --closure-size -h $(readlink -f 'result-pi4b')

  - name: Push pi4b to Attic
    image: bash
    environment:
      ATTIC_KEY:
        from_secret: attic_key
    commands:
      - attic push lounge-rocks:nix-cache 'result-pi4b'

when:
  event:
    - manual
    - push
  branch:
    - main
    - update_flake_lock_action
