steps:
  - name: Build Pi4B Image
    image: bash
    commands:
      - nix build --print-out-paths '.#nixosConfigurations.pi4b.config.system.build.sdImage'

  - name: Show image Size
    image: bash
    commands:
      - nix path-info --closure-size -h $(readlink -f 'result')

  - name: Upload to S3
    image: bash
    environment:
      S3_URL: https://s3.eu-central-003.backblazeb2.com
      S3_BUCKET: crab-share
      S3_REGION: eu-central-003
      S3_ACCESS_KEY: 003d560892a1b3a0000000002
      S3_SECRET_KEY: $S3_SECRET_KEY
    commands:
      - crab_share --expires 7d --purge --zip-single-file -c bzip2 result/sd-image/pi4b-image-*-aarch64-linux.img

labels:
  backend: local
  platform: linux/arm64

when:
  event: manual
