labels:
  backend: local
  platform: linux/amd64

steps:
    - name: Show Flake
      image: bash
      commands:
      - nix flake show
    - name: Show Flake Info 
      image: bash
      commands:
        - nix flake info
    - name: Check Flake
      image: bash
      commands:
        - nix flake check --all-systems --print-build-logs

when:
  event:
    - manual
    - push
  branch:
    - main
    - update_flake_lock_action
